#!/bin/bash

. config.sh

STACK=$1
RESOURCE=$2

find_event() {
    $@ 2>/dev/null | grep -o "\"href\": \"http://[^\"]*\", \"rel\": \"self\"" | tail -n 1 | sed -e "s#\"href\": \"http://localhost:8004\(/v1/[^\"]*\)\".*#\1#"
}

if [ -n "$RESOURCE" ]; then
    event_list="resource-event-list"
else
    event_list="stack-event-list"
fi

EVENT=`find_event $(dirname $0)/$event_list $STACK $RESOURCE`

$(dirname $0)/get $PORT $EVENT
